import { FormEvent, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Clock, Instagram, Mail, MapPin, MessageCircle } from "lucide-react";
import { storeConfig } from "@/config/storeConfig";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
export const Route = createFileRoute("/contato")({ head: () => ({ meta: [{ title: "Entre em contato — Fabia Multimarcas" }, { name: "description", content: "Fale com a Fabia Multimarcas por WhatsApp, Instagram ou e-mail." }, { property: "og:title", content: "Entre em contato — Fabia Multimarcas" }, { property: "og:description", content: "Atendimento personalizado para encontrar sua próxima peça favorita." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ContactPage });
function ContactPage() { const [sent, setSent] = useState(false); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); } return <main><section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><p className="eyebrow text-primary-foreground/70">Atendimento</p><h1 className="mt-3 font-serif text-5xl md:text-7xl">Entre em contato</h1><p className="mt-4 max-w-xl text-primary-foreground/75">Estamos por perto para ajudar você a escolher, tirar dúvidas e conhecer as novidades.</p></div></section><section className="mx-auto grid max-w-7xl gap-12 px-5 py-14 md:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:py-20"><div><h2 className="font-serif text-3xl">Fale com a Fabia</h2><div className="mt-8 space-y-6 text-sm"><a className="contact-line" href={`https://wa.me/${storeConfig.whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle /> <span><strong>WhatsApp</strong><small>{storeConfig.whatsappDisplay}</small></span></a><a className="contact-line" href={storeConfig.instagramUrl} target="_blank" rel="noreferrer"><Instagram /><span><strong>Instagram</strong><small>{storeConfig.instagram}</small></span></a><a className="contact-line" href={`mailto:${storeConfig.email}`}><Mail /><span><strong>E-mail</strong><small>{storeConfig.email}</small></span></a><div className="contact-line"><MapPin /><span><strong>Endereço</strong><small>{storeConfig.endereco}</small></span></div><div className="contact-line"><Clock /><span><strong>Horário</strong><small>{storeConfig.horario}</small></span></div></div></div><form onSubmit={submit} className="border border-border bg-surface p-5 md:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="field-label">Nome<Input required placeholder="Seu nome" /></label><label className="field-label">E-mail<Input required type="email" placeholder="voce@email.com" /></label><label className="field-label sm:col-span-2">Telefone<Input required type="tel" placeholder="(00) 00000-0000" /></label><label className="field-label sm:col-span-2">Mensagem<Textarea required rows={5} placeholder="Como podemos ajudar?" /></label></div><Button type="submit" size="lg" className="mt-6 w-full sm:w-auto">Enviar mensagem</Button>{sent && <p role="status" className="mt-4 text-sm text-success">Mensagem registrada. Em breve entraremos em contato.</p>}</form></section><section className="border-t border-border bg-surface"><div className="mx-auto max-w-7xl px-5 py-14 md:px-8"><div className="grid min-h-64 place-items-center border border-dashed border-border bg-background text-center"><div><MapPin className="mx-auto size-7 text-primary" /><p className="mt-3 font-serif text-2xl">Localização da loja</p><p className="mt-1 text-sm text-muted-foreground">Área preparada para receber o mapa.</p></div></div></div></section></main>; }
