import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, MessageCircle, X } from "lucide-react";
import { getProductById } from "@/data/products";
import { storeConfig } from "@/config/storeConfig";
import { formatPrice } from "@/utils/format";
import { ProductGallery } from "@/components/store/ProductGallery";
import { Button } from "@/components/ui/button";
export const Route = createFileRoute("/produto/$id")({ head: ({ params }) => { const product = getProductById(Number(params.id)); const title = product ? `${product.nome} — Fabia Multimarcas` : "Produto — Fabia Multimarcas"; const description = product?.descricao ?? "Conheça a seleção de produtos da Fabia Multimarcas."; return { meta: [{ title }, { name: "description", content: description }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }; }, component: ProductPage });
function ProductPage() { const { id } = Route.useParams(); const product = getProductById(Number(id)); if (!product) return <main className="mx-auto max-w-3xl px-5 py-24 text-center"><p className="eyebrow">Produto indisponível</p><h1 className="mt-4 font-serif text-5xl">Não encontramos esta peça.</h1><Button asChild className="mt-8"><Link to="/">Voltar ao início</Link></Button></main>; const message = `Olá! Tenho interesse no produto ${product.nome}, da marca ${product.marca}.`; return <main className="mx-auto max-w-7xl px-5 py-10 md:px-8 md:py-16"><div className="grid gap-10 lg:grid-cols-[1.15fr_0.85fr] lg:gap-20"><ProductGallery images={product.imagens} name={product.nome} /><section className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow">{product.marca} · {product.categoria}</p><h1 className="mt-3 font-serif text-4xl leading-tight md:text-6xl">{product.nome}</h1><p className="mt-5 text-2xl font-semibold">{formatPrice(product.preco)}</p><p className="mt-7 leading-relaxed text-muted-foreground">{product.descricao}</p><div className="mt-8"><p className="text-xs font-semibold uppercase tracking-[0.14em]">Tamanhos disponíveis</p><div className="mt-3 flex flex-wrap gap-2">{product.tamanhos.map((size) => <span key={size} className="grid min-h-11 min-w-11 place-items-center border border-border px-3 text-sm">{size}</span>)}</div></div><div className="mt-7 flex items-center gap-2 text-sm">{product.disponibilidade ? <><Check className="size-4 text-success" /> Disponível</> : <><X className="size-4 text-destructive" /> Temporariamente indisponível</>}</div><Button asChild size="lg" className="mt-8 w-full" disabled={!product.disponibilidade}><a href={`https://wa.me/${storeConfig.whatsapp}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer"><MessageCircle /> Tenho interesse</a></Button><p className="mt-4 text-center text-xs text-muted-foreground">Você será direcionado ao atendimento pelo WhatsApp.</p></section></div></main>; }
